### ISSUE TITLE
persistent state not working

### ISSUE THREAD

**Issue by gothmog123** [ChrisAntaki/disable-webrtc-firefox#15]
even if you tick the box, the button state is not saved on a restart

**Comment by ChrisAntaki** [comment]
Hey @gothmog123 , thanks for pointing this out, I'm checking into it now

**Comment by ChrisAntaki** [comment]
This bug should be fixed by https://github.com/ChrisAntaki/disable-webrtc-firefox/commit/46fb1bb5b46ba9831d454b302fe8734890aa051c . There's a new version waiting for approval on AMO: https://addons.mozilla.org/en-US/firefox/addon/happy-bonobo-disable-webrtc/versions/?page=1#version-1.0.16

Thanks again

**Comment by gothmog123** [comment]
thank you!
