### ISSUE TITLE
Verbosity in status message

### ISSUE THREAD

**Issue by ddnomad** [ChrisAntaki/disable-webrtc-firefox#23]
Hi!

It's a nice plugin. Though I would suggest you to change a status label when WebRTC is enabled (because a current one is slightly confusing). So my proposed change:

`WebRTC is not disabled. Be careful.` => `WebRTC is *enabled*. Be careful.`

The thing is that the double negation "not disabled" might be overlooked by a user such as me. After locating the word "disabled" I assume that everything is OK. 

Thanks for considering my issue.

Best regards,
dd

**Comment by ChrisAntaki** [comment]
Thanks for bringing this up, @ddnomad. I wanted to avoid using the word "enabled", since someone who wasn't paying attention might think that meant the plugin was enabled. I like your idea of using stars to highlight a word though. What if they highlighted the negation? "WebRTC is \*not\* disabled. Be careful."

**Comment by ddnomad** [comment]
Well, for me a combination "not disabled" itself looks rather weird. Though stressing on *not* or even *NOT* (which is too much of a stressing but I like it) would be definitely better then a present formulation.

**Comment by ChrisAntaki** [comment]
Thanks for bringing this up. Fixed by 3fdc675deef37a15fb3486d152cd4eef89fab865.
