### ISSUE TITLE
disable-webrtc blocks google voice

### ISSUE THREAD

**Issue by subscriptionblocker** [ChrisAntaki/disable-webrtc-firefox#27]
https://productforums.google.com/forum/#!topic/voice/6pAlxoo_83o;context-place=forum/voice

Confirmed. Firefox leaks without your addon, but google voice is definitely killed. Confirmed.

Try to imagine how hard this is to explain to your wife :(

**Comment by karlbright** [comment]
I've been looking into how this could be handled via extension, but there are a few complications.

Testing via meet.google.com I was able to enable WebRTC via this extension, load the page, join a call successfully, and then disable WebRTC again via the extension. This did not affect the call at all as the connection had already been established and it's safe to assume at this point that IP leak is most likely. Which in some cases you may wish to do, like you said.

The problem with trying to add something like a filter list to this extension is:

1. The settings to enable/disable WebRTC is within browser settings and can not be set per tab or host. Enabling it (even temporarily) for a given page would enable it browser wide and that opens up the chance of another page creating a connection without your permission. Users would have to be aware of this.

2. After messing around with some possible solutions, I was unable to clearly define a point where we can safely enable and disable WebRTC when requesting a page that uses it, such as meet.google.com. The issue here is that using something like `browser.webNavigation` will provide an `onCompleted` event listener, but disabling WebRTC at that point will cause a race condition between the page scripts creating a connection, and the setting toggle.

3. It's possible that with the use of `activeTab` extension permissions, we may be able to use `browser.tabs.executeScript` to ensure that we listen for connections being made, enable WebRTC and disable it once that connection has been established for a given host filter. But that still opens up other pages to make connections temporarily, and there are also issues with what script would be executed. Unfortunately RTCPeerConnection events do not bubble, so my initial thoughts for this would be to wrap the existing RTCPeerConnection, which may not even be possible, and if it is, it feels like a horrible solution and flakey at best.

I'll have another look into this and see if I can find a solution that doesn't feel too bad, but the best solution for the foreseeable future is to either have another browser (perhaps firefox developer edition without this extension) used for those services, or enable WebRTC, and disable it again once finished.

**Comment by ChrisAntaki** [comment]
Thanks for researching this. Having a backup browser does seem like the best option here.

**Comment by markwr** [comment]
I would have also liked to somehow "whitelist" https://voice.google.com
I don't make calls there, but just want to see the history of who called me, or texted, or left voice mail.
Currently I have to toggle WebRTC off to see my Google Voice history.

**Comment by ChrisAntaki** [comment]
Thanks again @karlbright for your research. I added a snippet of your comment to the README and addon description.
